name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Major: '1'
      Minor: '0'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Common.sln --no-cache --force-evaluate --configfile nuget.config
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: dotnet build Common.sln --configuration Release --no-restore

      - name: Pack NuGet packages
        run: dotnet pack Common.sln --configuration Release --no-build --output ./nupkgs /p:Version=${{ env.Major }}.${{ env.Minor }}.${{ github.run_number }}

      - name: Publish to GitHub Packages
        run: |
          for f in ./nupkgs/*.nupkg; do
            dotnet nuget push "$f" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
          done
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add GitHub Packages source
        run: dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name "github" --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text --configfile nuget.config

